version: '3.8'

services:
  web:
    build: .
    container_name: nextjs_app
    ports:
      - "3000:3000"
    env_file:
      - .env
    depends_on:
      - db
    networks:
      - app-network

  db:
    image: postgres:15
    container_name: postgres_db
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: nextauth
    volumes:
      - ./db_folder:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    networks:
      - app-network

# volumes:
#   postgres_data:

networks:
  app-network:
    driver: bridge
